/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWorkIndexRouteImport } from './routes/_authenticated/work/index'
import { Route as AuthenticatedTrainingIndexRouteImport } from './routes/_authenticated/training/index'
import { Route as AuthenticatedTimesheetsIndexRouteImport } from './routes/_authenticated/timesheets/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedSchedulingIndexRouteImport } from './routes/_authenticated/scheduling/index'
import { Route as AuthenticatedRotaIndexRouteImport } from './routes/_authenticated/rota/index'
import { Route as AuthenticatedRosterIndexRouteImport } from './routes/_authenticated/roster/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProcurementIndexRouteImport } from './routes/_authenticated/procurement/index'
import { Route as AuthenticatedPolicyIndexRouteImport } from './routes/_authenticated/policy/index'
import { Route as AuthenticatedOpsReadinessIndexRouteImport } from './routes/_authenticated/ops-readiness/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedNocPerformanceIndexRouteImport } from './routes/_authenticated/noc-performance/index'
import { Route as AuthenticatedLeaveIndexRouteImport } from './routes/_authenticated/leave/index'
import { Route as AuthenticatedLatenessIndexRouteImport } from './routes/_authenticated/lateness/index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents/index'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as AuthenticatedHrIndexRouteImport } from './routes/_authenticated/hr/index'
import { Route as AuthenticatedFormsIndexRouteImport } from './routes/_authenticated/forms/index'
import { Route as AuthenticatedCyclesIndexRouteImport } from './routes/_authenticated/cycles/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as AuthenticatedChangesIndexRouteImport } from './routes/_authenticated/changes/index'
import { Route as AuthenticatedCareerProgressionIndexRouteImport } from './routes/_authenticated/career-progression/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated/attendance/index'
import { Route as AuthenticatedAppraisalsIndexRouteImport } from './routes/_authenticated/appraisals/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedAdvancesIndexRouteImport } from './routes/_authenticated/advances/index'
import { Route as AuthenticatedAccessIndexRouteImport } from './routes/_authenticated/access/index'
import { Route as AuthenticatedWorkWorkloadRouteImport } from './routes/_authenticated/work/workload'
import { Route as AuthenticatedWorkNewRouteImport } from './routes/_authenticated/work/new'
import { Route as AuthenticatedWorkWorkItemIdRouteImport } from './routes/_authenticated/work/$workItemId'
import { Route as AuthenticatedTrainingVouchersRouteImport } from './routes/_authenticated/training/vouchers'
import { Route as AuthenticatedTrainingPlanRouteImport } from './routes/_authenticated/training/plan'
import { Route as AuthenticatedTrainingInHouseRouteImport } from './routes/_authenticated/training/in-house'
import { Route as AuthenticatedTrainingExamsRouteImport } from './routes/_authenticated/training/exams'
import { Route as AuthenticatedTrainingEventsRouteImport } from './routes/_authenticated/training/events'
import { Route as AuthenticatedTrainingCatalogRouteImport } from './routes/_authenticated/training/catalog'
import { Route as AuthenticatedTimesheetsDocumentsRouteImport } from './routes/_authenticated/timesheets/documents'
import { Route as AuthenticatedStaffStaffIdRouteImport } from './routes/_authenticated/staff/$staffId'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsLeaveTypesRouteImport } from './routes/_authenticated/settings/leave-types'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings/general'
import { Route as AuthenticatedSettingsEscalationRouteImport } from './routes/_authenticated/settings/escalation'
import { Route as AuthenticatedSettingsDepartmentsRouteImport } from './routes/_authenticated/settings/departments'
import { Route as AuthenticatedSettingsDepartmentAssignmentsRouteImport } from './routes/_authenticated/settings/department-assignments'
import { Route as AuthenticatedSettingsAutomationRouteImport } from './routes/_authenticated/settings/automation'
import { Route as AuthenticatedSchedulingNocShiftsRouteImport } from './routes/_authenticated/scheduling/noc-shifts'
import { Route as AuthenticatedSchedulingMaintenanceRouteImport } from './routes/_authenticated/scheduling/maintenance'
import { Route as AuthenticatedSchedulingDcsOncallRouteImport } from './routes/_authenticated/scheduling/dcs-oncall'
import { Route as AuthenticatedRotaSwapsRouteImport } from './routes/_authenticated/rota/swaps'
import { Route as AuthenticatedRotaPlannerRouteImport } from './routes/_authenticated/rota/planner'
import { Route as AuthenticatedRotaHistoryRouteImport } from './routes/_authenticated/rota/history'
import { Route as AuthenticatedRosterTodayRouteImport } from './routes/_authenticated/roster/today'
import { Route as AuthenticatedRosterSwapsRouteImport } from './routes/_authenticated/roster/swaps'
import { Route as AuthenticatedRosterPlannerRouteImport } from './routes/_authenticated/roster/planner'
import { Route as AuthenticatedRosterMyRosterRouteImport } from './routes/_authenticated/roster/my-roster'
import { Route as AuthenticatedRosterMaintenanceRouteImport } from './routes/_authenticated/roster/maintenance'
import { Route as AuthenticatedProcurementNewRouteImport } from './routes/_authenticated/procurement/new'
import { Route as AuthenticatedLeaveTosdRouteImport } from './routes/_authenticated/leave/tosd'
import { Route as AuthenticatedLeavePlannerRouteImport } from './routes/_authenticated/leave/planner'
import { Route as AuthenticatedLeaveNewRouteImport } from './routes/_authenticated/leave/new'
import { Route as AuthenticatedLeaveCalendarRouteImport } from './routes/_authenticated/leave/calendar'
import { Route as AuthenticatedLeaveBalancesRouteImport } from './routes/_authenticated/leave/balances'
import { Route as AuthenticatedIncidentsNewRouteImport } from './routes/_authenticated/incidents/new'
import { Route as AuthenticatedIncidentsIncidentIdRouteImport } from './routes/_authenticated/incidents/$incidentId'
import { Route as AuthenticatedHrPpeRouteImport } from './routes/_authenticated/hr/ppe'
import { Route as AuthenticatedCyclesCycleIdRouteImport } from './routes/_authenticated/cycles/$cycleId'
import { Route as AuthenticatedContractsContractIdRouteImport } from './routes/_authenticated/contracts/$contractId'
import { Route as AuthenticatedComplianceTrainingRouteImport } from './routes/_authenticated/compliance/training'
import { Route as AuthenticatedCompliancePpeRouteImport } from './routes/_authenticated/compliance/ppe'
import { Route as AuthenticatedComplianceItemsRouteImport } from './routes/_authenticated/compliance/items'
import { Route as AuthenticatedChangesNewRouteImport } from './routes/_authenticated/changes/new'
import { Route as AuthenticatedChangesChangeIdRouteImport } from './routes/_authenticated/changes/$changeId'
import { Route as AuthenticatedAttendanceRollCallRouteImport } from './routes/_authenticated/attendance/roll-call'
import { Route as AuthenticatedAttendanceMonthlyRouteImport } from './routes/_authenticated/attendance/monthly'
import { Route as AuthenticatedAttendanceHolidaysRouteImport } from './routes/_authenticated/attendance/holidays'
import { Route as AuthenticatedAppraisalsInboxRouteImport } from './routes/_authenticated/appraisals/inbox'
import { Route as AuthenticatedAppraisalsAppraisalIdRouteImport } from './routes/_authenticated/appraisals/$appraisalId'
import { Route as AuthenticatedAdvancesNewRouteImport } from './routes/_authenticated/advances/new'
import { Route as AuthenticatedAdvancesAdvanceIdRouteImport } from './routes/_authenticated/advances/$advanceId'
import { Route as AuthenticatedAccessRegistryRouteImport } from './routes/_authenticated/access/registry'
import { Route as AuthenticatedAccessPlatformsRouteImport } from './routes/_authenticated/access/platforms'
import { Route as AuthenticatedAccessAccountIdRouteImport } from './routes/_authenticated/access/$accountId'
import { Route as AuthenticatedRotaWarningsIndexRouteImport } from './routes/_authenticated/rota/warnings/index'
import { Route as AuthenticatedRotaFairnessIndexRouteImport } from './routes/_authenticated/rota/fairness/index'
import { Route as AuthenticatedRotaCalendarIndexRouteImport } from './routes/_authenticated/rota/calendar/index'
import { Route as AuthenticatedStaffStaffIdAttendanceRouteImport } from './routes/_authenticated/staff.$staffId.attendance'
import { Route as AuthenticatedAppraisalsStaffStaffProfileIdRouteImport } from './routes/_authenticated/appraisals/staff/$staffProfileId'
import { Route as AuthenticatedAccessRegistryStaffIdRouteImport } from './routes/_authenticated/access/registry.$staffId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkIndexRoute = AuthenticatedWorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrainingIndexRoute =
  AuthenticatedTrainingIndexRouteImport.update({
    id: '/training/',
    path: '/training/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimesheetsIndexRoute =
  AuthenticatedTimesheetsIndexRouteImport.update({
    id: '/timesheets/',
    path: '/timesheets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulingIndexRoute =
  AuthenticatedSchedulingIndexRouteImport.update({
    id: '/scheduling/',
    path: '/scheduling/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaIndexRoute = AuthenticatedRotaIndexRouteImport.update({
  id: '/rota/',
  path: '/rota/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRosterIndexRoute =
  AuthenticatedRosterIndexRouteImport.update({
    id: '/roster/',
    path: '/roster/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementIndexRoute =
  AuthenticatedProcurementIndexRouteImport.update({
    id: '/procurement/',
    path: '/procurement/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPolicyIndexRoute =
  AuthenticatedPolicyIndexRouteImport.update({
    id: '/policy/',
    path: '/policy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsReadinessIndexRoute =
  AuthenticatedOpsReadinessIndexRouteImport.update({
    id: '/ops-readiness/',
    path: '/ops-readiness/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNocPerformanceIndexRoute =
  AuthenticatedNocPerformanceIndexRouteImport.update({
    id: '/noc-performance/',
    path: '/noc-performance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveIndexRoute = AuthenticatedLeaveIndexRouteImport.update({
  id: '/leave/',
  path: '/leave/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLatenessIndexRoute =
  AuthenticatedLatenessIndexRouteImport.update({
    id: '/lateness/',
    path: '/lateness/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/incidents/',
    path: '/incidents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrIndexRoute = AuthenticatedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFormsIndexRoute = AuthenticatedFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCyclesIndexRoute =
  AuthenticatedCyclesIndexRouteImport.update({
    id: '/cycles/',
    path: '/cycles/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/compliance/',
    path: '/compliance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangesIndexRoute =
  AuthenticatedChangesIndexRouteImport.update({
    id: '/changes/',
    path: '/changes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCareerProgressionIndexRoute =
  AuthenticatedCareerProgressionIndexRouteImport.update({
    id: '/career-progression/',
    path: '/career-progression/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppraisalsIndexRoute =
  AuthenticatedAppraisalsIndexRouteImport.update({
    id: '/appraisals/',
    path: '/appraisals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvancesIndexRoute =
  AuthenticatedAdvancesIndexRouteImport.update({
    id: '/advances/',
    path: '/advances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessIndexRoute =
  AuthenticatedAccessIndexRouteImport.update({
    id: '/access/',
    path: '/access/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkWorkloadRoute =
  AuthenticatedWorkWorkloadRouteImport.update({
    id: '/work/workload',
    path: '/work/workload',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkNewRoute = AuthenticatedWorkNewRouteImport.update({
  id: '/work/new',
  path: '/work/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkWorkItemIdRoute =
  AuthenticatedWorkWorkItemIdRouteImport.update({
    id: '/work/$workItemId',
    path: '/work/$workItemId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingVouchersRoute =
  AuthenticatedTrainingVouchersRouteImport.update({
    id: '/training/vouchers',
    path: '/training/vouchers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingPlanRoute =
  AuthenticatedTrainingPlanRouteImport.update({
    id: '/training/plan',
    path: '/training/plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingInHouseRoute =
  AuthenticatedTrainingInHouseRouteImport.update({
    id: '/training/in-house',
    path: '/training/in-house',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingExamsRoute =
  AuthenticatedTrainingExamsRouteImport.update({
    id: '/training/exams',
    path: '/training/exams',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingEventsRoute =
  AuthenticatedTrainingEventsRouteImport.update({
    id: '/training/events',
    path: '/training/events',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingCatalogRoute =
  AuthenticatedTrainingCatalogRouteImport.update({
    id: '/training/catalog',
    path: '/training/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTimesheetsDocumentsRoute =
  AuthenticatedTimesheetsDocumentsRouteImport.update({
    id: '/timesheets/documents',
    path: '/timesheets/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffStaffIdRoute =
  AuthenticatedStaffStaffIdRouteImport.update({
    id: '/staff/$staffId',
    path: '/staff/$staffId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsLeaveTypesRoute =
  AuthenticatedSettingsLeaveTypesRouteImport.update({
    id: '/settings/leave-types',
    path: '/settings/leave-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsEscalationRoute =
  AuthenticatedSettingsEscalationRouteImport.update({
    id: '/settings/escalation',
    path: '/settings/escalation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDepartmentsRoute =
  AuthenticatedSettingsDepartmentsRouteImport.update({
    id: '/settings/departments',
    path: '/settings/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsDepartmentAssignmentsRoute =
  AuthenticatedSettingsDepartmentAssignmentsRouteImport.update({
    id: '/settings/department-assignments',
    path: '/settings/department-assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsAutomationRoute =
  AuthenticatedSettingsAutomationRouteImport.update({
    id: '/settings/automation',
    path: '/settings/automation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulingNocShiftsRoute =
  AuthenticatedSchedulingNocShiftsRouteImport.update({
    id: '/scheduling/noc-shifts',
    path: '/scheduling/noc-shifts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulingMaintenanceRoute =
  AuthenticatedSchedulingMaintenanceRouteImport.update({
    id: '/scheduling/maintenance',
    path: '/scheduling/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedulingDcsOncallRoute =
  AuthenticatedSchedulingDcsOncallRouteImport.update({
    id: '/scheduling/dcs-oncall',
    path: '/scheduling/dcs-oncall',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaSwapsRoute = AuthenticatedRotaSwapsRouteImport.update({
  id: '/rota/swaps',
  path: '/rota/swaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotaPlannerRoute =
  AuthenticatedRotaPlannerRouteImport.update({
    id: '/rota/planner',
    path: '/rota/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaHistoryRoute =
  AuthenticatedRotaHistoryRouteImport.update({
    id: '/rota/history',
    path: '/rota/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterTodayRoute =
  AuthenticatedRosterTodayRouteImport.update({
    id: '/roster/today',
    path: '/roster/today',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterSwapsRoute =
  AuthenticatedRosterSwapsRouteImport.update({
    id: '/roster/swaps',
    path: '/roster/swaps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterPlannerRoute =
  AuthenticatedRosterPlannerRouteImport.update({
    id: '/roster/planner',
    path: '/roster/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterMyRosterRoute =
  AuthenticatedRosterMyRosterRouteImport.update({
    id: '/roster/my-roster',
    path: '/roster/my-roster',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRosterMaintenanceRoute =
  AuthenticatedRosterMaintenanceRouteImport.update({
    id: '/roster/maintenance',
    path: '/roster/maintenance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementNewRoute =
  AuthenticatedProcurementNewRouteImport.update({
    id: '/procurement/new',
    path: '/procurement/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveTosdRoute = AuthenticatedLeaveTosdRouteImport.update({
  id: '/leave/tosd',
  path: '/leave/tosd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeavePlannerRoute =
  AuthenticatedLeavePlannerRouteImport.update({
    id: '/leave/planner',
    path: '/leave/planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveNewRoute = AuthenticatedLeaveNewRouteImport.update({
  id: '/leave/new',
  path: '/leave/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaveCalendarRoute =
  AuthenticatedLeaveCalendarRouteImport.update({
    id: '/leave/calendar',
    path: '/leave/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaveBalancesRoute =
  AuthenticatedLeaveBalancesRouteImport.update({
    id: '/leave/balances',
    path: '/leave/balances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsNewRoute =
  AuthenticatedIncidentsNewRouteImport.update({
    id: '/incidents/new',
    path: '/incidents/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIncidentsIncidentIdRoute =
  AuthenticatedIncidentsIncidentIdRouteImport.update({
    id: '/incidents/$incidentId',
    path: '/incidents/$incidentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHrPpeRoute = AuthenticatedHrPpeRouteImport.update({
  id: '/hr/ppe',
  path: '/hr/ppe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCyclesCycleIdRoute =
  AuthenticatedCyclesCycleIdRouteImport.update({
    id: '/cycles/$cycleId',
    path: '/cycles/$cycleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsContractIdRoute =
  AuthenticatedContractsContractIdRouteImport.update({
    id: '/contracts/$contractId',
    path: '/contracts/$contractId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceTrainingRoute =
  AuthenticatedComplianceTrainingRouteImport.update({
    id: '/compliance/training',
    path: '/compliance/training',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompliancePpeRoute =
  AuthenticatedCompliancePpeRouteImport.update({
    id: '/compliance/ppe',
    path: '/compliance/ppe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceItemsRoute =
  AuthenticatedComplianceItemsRouteImport.update({
    id: '/compliance/items',
    path: '/compliance/items',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChangesNewRoute = AuthenticatedChangesNewRouteImport.update({
  id: '/changes/new',
  path: '/changes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangesChangeIdRoute =
  AuthenticatedChangesChangeIdRouteImport.update({
    id: '/changes/$changeId',
    path: '/changes/$changeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceRollCallRoute =
  AuthenticatedAttendanceRollCallRouteImport.update({
    id: '/attendance/roll-call',
    path: '/attendance/roll-call',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceMonthlyRoute =
  AuthenticatedAttendanceMonthlyRouteImport.update({
    id: '/attendance/monthly',
    path: '/attendance/monthly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAttendanceHolidaysRoute =
  AuthenticatedAttendanceHolidaysRouteImport.update({
    id: '/attendance/holidays',
    path: '/attendance/holidays',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppraisalsInboxRoute =
  AuthenticatedAppraisalsInboxRouteImport.update({
    id: '/appraisals/inbox',
    path: '/appraisals/inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppraisalsAppraisalIdRoute =
  AuthenticatedAppraisalsAppraisalIdRouteImport.update({
    id: '/appraisals/$appraisalId',
    path: '/appraisals/$appraisalId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvancesNewRoute =
  AuthenticatedAdvancesNewRouteImport.update({
    id: '/advances/new',
    path: '/advances/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvancesAdvanceIdRoute =
  AuthenticatedAdvancesAdvanceIdRouteImport.update({
    id: '/advances/$advanceId',
    path: '/advances/$advanceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessRegistryRoute =
  AuthenticatedAccessRegistryRouteImport.update({
    id: '/access/registry',
    path: '/access/registry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessPlatformsRoute =
  AuthenticatedAccessPlatformsRouteImport.update({
    id: '/access/platforms',
    path: '/access/platforms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessAccountIdRoute =
  AuthenticatedAccessAccountIdRouteImport.update({
    id: '/access/$accountId',
    path: '/access/$accountId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaWarningsIndexRoute =
  AuthenticatedRotaWarningsIndexRouteImport.update({
    id: '/rota/warnings/',
    path: '/rota/warnings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaFairnessIndexRoute =
  AuthenticatedRotaFairnessIndexRouteImport.update({
    id: '/rota/fairness/',
    path: '/rota/fairness/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRotaCalendarIndexRoute =
  AuthenticatedRotaCalendarIndexRouteImport.update({
    id: '/rota/calendar/',
    path: '/rota/calendar/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffStaffIdAttendanceRoute =
  AuthenticatedStaffStaffIdAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedStaffStaffIdRoute,
  } as any)
const AuthenticatedAppraisalsStaffStaffProfileIdRoute =
  AuthenticatedAppraisalsStaffStaffProfileIdRouteImport.update({
    id: '/appraisals/staff/$staffProfileId',
    path: '/appraisals/staff/$staffProfileId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccessRegistryStaffIdRoute =
  AuthenticatedAccessRegistryStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedAccessRegistryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/access/$accountId': typeof AuthenticatedAccessAccountIdRoute
  '/access/platforms': typeof AuthenticatedAccessPlatformsRoute
  '/access/registry': typeof AuthenticatedAccessRegistryRouteWithChildren
  '/advances/$advanceId': typeof AuthenticatedAdvancesAdvanceIdRoute
  '/advances/new': typeof AuthenticatedAdvancesNewRoute
  '/appraisals/$appraisalId': typeof AuthenticatedAppraisalsAppraisalIdRoute
  '/appraisals/inbox': typeof AuthenticatedAppraisalsInboxRoute
  '/attendance/holidays': typeof AuthenticatedAttendanceHolidaysRoute
  '/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/attendance/roll-call': typeof AuthenticatedAttendanceRollCallRoute
  '/changes/$changeId': typeof AuthenticatedChangesChangeIdRoute
  '/changes/new': typeof AuthenticatedChangesNewRoute
  '/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/cycles/$cycleId': typeof AuthenticatedCyclesCycleIdRoute
  '/hr/ppe': typeof AuthenticatedHrPpeRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/leave/balances': typeof AuthenticatedLeaveBalancesRoute
  '/leave/calendar': typeof AuthenticatedLeaveCalendarRoute
  '/leave/new': typeof AuthenticatedLeaveNewRoute
  '/leave/planner': typeof AuthenticatedLeavePlannerRoute
  '/leave/tosd': typeof AuthenticatedLeaveTosdRoute
  '/procurement/new': typeof AuthenticatedProcurementNewRoute
  '/roster/maintenance': typeof AuthenticatedRosterMaintenanceRoute
  '/roster/my-roster': typeof AuthenticatedRosterMyRosterRoute
  '/roster/planner': typeof AuthenticatedRosterPlannerRoute
  '/roster/swaps': typeof AuthenticatedRosterSwapsRoute
  '/roster/today': typeof AuthenticatedRosterTodayRoute
  '/rota/history': typeof AuthenticatedRotaHistoryRoute
  '/rota/planner': typeof AuthenticatedRotaPlannerRoute
  '/rota/swaps': typeof AuthenticatedRotaSwapsRoute
  '/scheduling/dcs-oncall': typeof AuthenticatedSchedulingDcsOncallRoute
  '/scheduling/maintenance': typeof AuthenticatedSchedulingMaintenanceRoute
  '/scheduling/noc-shifts': typeof AuthenticatedSchedulingNocShiftsRoute
  '/settings/automation': typeof AuthenticatedSettingsAutomationRoute
  '/settings/department-assignments': typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/escalation': typeof AuthenticatedSettingsEscalationRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRouteWithChildren
  '/timesheets/documents': typeof AuthenticatedTimesheetsDocumentsRoute
  '/training/catalog': typeof AuthenticatedTrainingCatalogRoute
  '/training/events': typeof AuthenticatedTrainingEventsRoute
  '/training/exams': typeof AuthenticatedTrainingExamsRoute
  '/training/in-house': typeof AuthenticatedTrainingInHouseRoute
  '/training/plan': typeof AuthenticatedTrainingPlanRoute
  '/training/vouchers': typeof AuthenticatedTrainingVouchersRoute
  '/work/$workItemId': typeof AuthenticatedWorkWorkItemIdRoute
  '/work/new': typeof AuthenticatedWorkNewRoute
  '/work/workload': typeof AuthenticatedWorkWorkloadRoute
  '/access/': typeof AuthenticatedAccessIndexRoute
  '/advances/': typeof AuthenticatedAdvancesIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/appraisals/': typeof AuthenticatedAppraisalsIndexRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/career-progression/': typeof AuthenticatedCareerProgressionIndexRoute
  '/changes/': typeof AuthenticatedChangesIndexRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/cycles/': typeof AuthenticatedCyclesIndexRoute
  '/forms/': typeof AuthenticatedFormsIndexRoute
  '/hr/': typeof AuthenticatedHrIndexRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/lateness/': typeof AuthenticatedLatenessIndexRoute
  '/leave/': typeof AuthenticatedLeaveIndexRoute
  '/noc-performance/': typeof AuthenticatedNocPerformanceIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/ops-readiness/': typeof AuthenticatedOpsReadinessIndexRoute
  '/policy/': typeof AuthenticatedPolicyIndexRoute
  '/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/roster/': typeof AuthenticatedRosterIndexRoute
  '/rota/': typeof AuthenticatedRotaIndexRoute
  '/scheduling/': typeof AuthenticatedSchedulingIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/timesheets/': typeof AuthenticatedTimesheetsIndexRoute
  '/training/': typeof AuthenticatedTrainingIndexRoute
  '/work/': typeof AuthenticatedWorkIndexRoute
  '/access/registry/$staffId': typeof AuthenticatedAccessRegistryStaffIdRoute
  '/appraisals/staff/$staffProfileId': typeof AuthenticatedAppraisalsStaffStaffProfileIdRoute
  '/staff/$staffId/attendance': typeof AuthenticatedStaffStaffIdAttendanceRoute
  '/rota/calendar/': typeof AuthenticatedRotaCalendarIndexRoute
  '/rota/fairness/': typeof AuthenticatedRotaFairnessIndexRoute
  '/rota/warnings/': typeof AuthenticatedRotaWarningsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/': typeof AuthenticatedIndexRoute
  '/access/$accountId': typeof AuthenticatedAccessAccountIdRoute
  '/access/platforms': typeof AuthenticatedAccessPlatformsRoute
  '/access/registry': typeof AuthenticatedAccessRegistryRouteWithChildren
  '/advances/$advanceId': typeof AuthenticatedAdvancesAdvanceIdRoute
  '/advances/new': typeof AuthenticatedAdvancesNewRoute
  '/appraisals/$appraisalId': typeof AuthenticatedAppraisalsAppraisalIdRoute
  '/appraisals/inbox': typeof AuthenticatedAppraisalsInboxRoute
  '/attendance/holidays': typeof AuthenticatedAttendanceHolidaysRoute
  '/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/attendance/roll-call': typeof AuthenticatedAttendanceRollCallRoute
  '/changes/$changeId': typeof AuthenticatedChangesChangeIdRoute
  '/changes/new': typeof AuthenticatedChangesNewRoute
  '/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/cycles/$cycleId': typeof AuthenticatedCyclesCycleIdRoute
  '/hr/ppe': typeof AuthenticatedHrPpeRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/leave/balances': typeof AuthenticatedLeaveBalancesRoute
  '/leave/calendar': typeof AuthenticatedLeaveCalendarRoute
  '/leave/new': typeof AuthenticatedLeaveNewRoute
  '/leave/planner': typeof AuthenticatedLeavePlannerRoute
  '/leave/tosd': typeof AuthenticatedLeaveTosdRoute
  '/procurement/new': typeof AuthenticatedProcurementNewRoute
  '/roster/maintenance': typeof AuthenticatedRosterMaintenanceRoute
  '/roster/my-roster': typeof AuthenticatedRosterMyRosterRoute
  '/roster/planner': typeof AuthenticatedRosterPlannerRoute
  '/roster/swaps': typeof AuthenticatedRosterSwapsRoute
  '/roster/today': typeof AuthenticatedRosterTodayRoute
  '/rota/history': typeof AuthenticatedRotaHistoryRoute
  '/rota/planner': typeof AuthenticatedRotaPlannerRoute
  '/rota/swaps': typeof AuthenticatedRotaSwapsRoute
  '/scheduling/dcs-oncall': typeof AuthenticatedSchedulingDcsOncallRoute
  '/scheduling/maintenance': typeof AuthenticatedSchedulingMaintenanceRoute
  '/scheduling/noc-shifts': typeof AuthenticatedSchedulingNocShiftsRoute
  '/settings/automation': typeof AuthenticatedSettingsAutomationRoute
  '/settings/department-assignments': typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  '/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/settings/escalation': typeof AuthenticatedSettingsEscalationRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/staff/$staffId': typeof AuthenticatedStaffStaffIdRouteWithChildren
  '/timesheets/documents': typeof AuthenticatedTimesheetsDocumentsRoute
  '/training/catalog': typeof AuthenticatedTrainingCatalogRoute
  '/training/events': typeof AuthenticatedTrainingEventsRoute
  '/training/exams': typeof AuthenticatedTrainingExamsRoute
  '/training/in-house': typeof AuthenticatedTrainingInHouseRoute
  '/training/plan': typeof AuthenticatedTrainingPlanRoute
  '/training/vouchers': typeof AuthenticatedTrainingVouchersRoute
  '/work/$workItemId': typeof AuthenticatedWorkWorkItemIdRoute
  '/work/new': typeof AuthenticatedWorkNewRoute
  '/work/workload': typeof AuthenticatedWorkWorkloadRoute
  '/access': typeof AuthenticatedAccessIndexRoute
  '/advances': typeof AuthenticatedAdvancesIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/appraisals': typeof AuthenticatedAppraisalsIndexRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/career-progression': typeof AuthenticatedCareerProgressionIndexRoute
  '/changes': typeof AuthenticatedChangesIndexRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/cycles': typeof AuthenticatedCyclesIndexRoute
  '/forms': typeof AuthenticatedFormsIndexRoute
  '/hr': typeof AuthenticatedHrIndexRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/lateness': typeof AuthenticatedLatenessIndexRoute
  '/leave': typeof AuthenticatedLeaveIndexRoute
  '/noc-performance': typeof AuthenticatedNocPerformanceIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/ops-readiness': typeof AuthenticatedOpsReadinessIndexRoute
  '/policy': typeof AuthenticatedPolicyIndexRoute
  '/procurement': typeof AuthenticatedProcurementIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/roster': typeof AuthenticatedRosterIndexRoute
  '/rota': typeof AuthenticatedRotaIndexRoute
  '/scheduling': typeof AuthenticatedSchedulingIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/timesheets': typeof AuthenticatedTimesheetsIndexRoute
  '/training': typeof AuthenticatedTrainingIndexRoute
  '/work': typeof AuthenticatedWorkIndexRoute
  '/access/registry/$staffId': typeof AuthenticatedAccessRegistryStaffIdRoute
  '/appraisals/staff/$staffProfileId': typeof AuthenticatedAppraisalsStaffStaffProfileIdRoute
  '/staff/$staffId/attendance': typeof AuthenticatedStaffStaffIdAttendanceRoute
  '/rota/calendar': typeof AuthenticatedRotaCalendarIndexRoute
  '/rota/fairness': typeof AuthenticatedRotaFairnessIndexRoute
  '/rota/warnings': typeof AuthenticatedRotaWarningsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/access/$accountId': typeof AuthenticatedAccessAccountIdRoute
  '/_authenticated/access/platforms': typeof AuthenticatedAccessPlatformsRoute
  '/_authenticated/access/registry': typeof AuthenticatedAccessRegistryRouteWithChildren
  '/_authenticated/advances/$advanceId': typeof AuthenticatedAdvancesAdvanceIdRoute
  '/_authenticated/advances/new': typeof AuthenticatedAdvancesNewRoute
  '/_authenticated/appraisals/$appraisalId': typeof AuthenticatedAppraisalsAppraisalIdRoute
  '/_authenticated/appraisals/inbox': typeof AuthenticatedAppraisalsInboxRoute
  '/_authenticated/attendance/holidays': typeof AuthenticatedAttendanceHolidaysRoute
  '/_authenticated/attendance/monthly': typeof AuthenticatedAttendanceMonthlyRoute
  '/_authenticated/attendance/roll-call': typeof AuthenticatedAttendanceRollCallRoute
  '/_authenticated/changes/$changeId': typeof AuthenticatedChangesChangeIdRoute
  '/_authenticated/changes/new': typeof AuthenticatedChangesNewRoute
  '/_authenticated/compliance/items': typeof AuthenticatedComplianceItemsRoute
  '/_authenticated/compliance/ppe': typeof AuthenticatedCompliancePpeRoute
  '/_authenticated/compliance/training': typeof AuthenticatedComplianceTrainingRoute
  '/_authenticated/contracts/$contractId': typeof AuthenticatedContractsContractIdRoute
  '/_authenticated/cycles/$cycleId': typeof AuthenticatedCyclesCycleIdRoute
  '/_authenticated/hr/ppe': typeof AuthenticatedHrPpeRoute
  '/_authenticated/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/_authenticated/incidents/new': typeof AuthenticatedIncidentsNewRoute
  '/_authenticated/leave/balances': typeof AuthenticatedLeaveBalancesRoute
  '/_authenticated/leave/calendar': typeof AuthenticatedLeaveCalendarRoute
  '/_authenticated/leave/new': typeof AuthenticatedLeaveNewRoute
  '/_authenticated/leave/planner': typeof AuthenticatedLeavePlannerRoute
  '/_authenticated/leave/tosd': typeof AuthenticatedLeaveTosdRoute
  '/_authenticated/procurement/new': typeof AuthenticatedProcurementNewRoute
  '/_authenticated/roster/maintenance': typeof AuthenticatedRosterMaintenanceRoute
  '/_authenticated/roster/my-roster': typeof AuthenticatedRosterMyRosterRoute
  '/_authenticated/roster/planner': typeof AuthenticatedRosterPlannerRoute
  '/_authenticated/roster/swaps': typeof AuthenticatedRosterSwapsRoute
  '/_authenticated/roster/today': typeof AuthenticatedRosterTodayRoute
  '/_authenticated/rota/history': typeof AuthenticatedRotaHistoryRoute
  '/_authenticated/rota/planner': typeof AuthenticatedRotaPlannerRoute
  '/_authenticated/rota/swaps': typeof AuthenticatedRotaSwapsRoute
  '/_authenticated/scheduling/dcs-oncall': typeof AuthenticatedSchedulingDcsOncallRoute
  '/_authenticated/scheduling/maintenance': typeof AuthenticatedSchedulingMaintenanceRoute
  '/_authenticated/scheduling/noc-shifts': typeof AuthenticatedSchedulingNocShiftsRoute
  '/_authenticated/settings/automation': typeof AuthenticatedSettingsAutomationRoute
  '/_authenticated/settings/department-assignments': typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  '/_authenticated/settings/departments': typeof AuthenticatedSettingsDepartmentsRoute
  '/_authenticated/settings/escalation': typeof AuthenticatedSettingsEscalationRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/leave-types': typeof AuthenticatedSettingsLeaveTypesRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/staff/$staffId': typeof AuthenticatedStaffStaffIdRouteWithChildren
  '/_authenticated/timesheets/documents': typeof AuthenticatedTimesheetsDocumentsRoute
  '/_authenticated/training/catalog': typeof AuthenticatedTrainingCatalogRoute
  '/_authenticated/training/events': typeof AuthenticatedTrainingEventsRoute
  '/_authenticated/training/exams': typeof AuthenticatedTrainingExamsRoute
  '/_authenticated/training/in-house': typeof AuthenticatedTrainingInHouseRoute
  '/_authenticated/training/plan': typeof AuthenticatedTrainingPlanRoute
  '/_authenticated/training/vouchers': typeof AuthenticatedTrainingVouchersRoute
  '/_authenticated/work/$workItemId': typeof AuthenticatedWorkWorkItemIdRoute
  '/_authenticated/work/new': typeof AuthenticatedWorkNewRoute
  '/_authenticated/work/workload': typeof AuthenticatedWorkWorkloadRoute
  '/_authenticated/access/': typeof AuthenticatedAccessIndexRoute
  '/_authenticated/advances/': typeof AuthenticatedAdvancesIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/appraisals/': typeof AuthenticatedAppraisalsIndexRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/career-progression/': typeof AuthenticatedCareerProgressionIndexRoute
  '/_authenticated/changes/': typeof AuthenticatedChangesIndexRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/cycles/': typeof AuthenticatedCyclesIndexRoute
  '/_authenticated/forms/': typeof AuthenticatedFormsIndexRoute
  '/_authenticated/hr/': typeof AuthenticatedHrIndexRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/lateness/': typeof AuthenticatedLatenessIndexRoute
  '/_authenticated/leave/': typeof AuthenticatedLeaveIndexRoute
  '/_authenticated/noc-performance/': typeof AuthenticatedNocPerformanceIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/ops-readiness/': typeof AuthenticatedOpsReadinessIndexRoute
  '/_authenticated/policy/': typeof AuthenticatedPolicyIndexRoute
  '/_authenticated/procurement/': typeof AuthenticatedProcurementIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/roster/': typeof AuthenticatedRosterIndexRoute
  '/_authenticated/rota/': typeof AuthenticatedRotaIndexRoute
  '/_authenticated/scheduling/': typeof AuthenticatedSchedulingIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/timesheets/': typeof AuthenticatedTimesheetsIndexRoute
  '/_authenticated/training/': typeof AuthenticatedTrainingIndexRoute
  '/_authenticated/work/': typeof AuthenticatedWorkIndexRoute
  '/_authenticated/access/registry/$staffId': typeof AuthenticatedAccessRegistryStaffIdRoute
  '/_authenticated/appraisals/staff/$staffProfileId': typeof AuthenticatedAppraisalsStaffStaffProfileIdRoute
  '/_authenticated/staff/$staffId/attendance': typeof AuthenticatedStaffStaffIdAttendanceRoute
  '/_authenticated/rota/calendar/': typeof AuthenticatedRotaCalendarIndexRoute
  '/_authenticated/rota/fairness/': typeof AuthenticatedRotaFairnessIndexRoute
  '/_authenticated/rota/warnings/': typeof AuthenticatedRotaWarningsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/access/$accountId'
    | '/access/platforms'
    | '/access/registry'
    | '/advances/$advanceId'
    | '/advances/new'
    | '/appraisals/$appraisalId'
    | '/appraisals/inbox'
    | '/attendance/holidays'
    | '/attendance/monthly'
    | '/attendance/roll-call'
    | '/changes/$changeId'
    | '/changes/new'
    | '/compliance/items'
    | '/compliance/ppe'
    | '/compliance/training'
    | '/contracts/$contractId'
    | '/cycles/$cycleId'
    | '/hr/ppe'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/leave/balances'
    | '/leave/calendar'
    | '/leave/new'
    | '/leave/planner'
    | '/leave/tosd'
    | '/procurement/new'
    | '/roster/maintenance'
    | '/roster/my-roster'
    | '/roster/planner'
    | '/roster/swaps'
    | '/roster/today'
    | '/rota/history'
    | '/rota/planner'
    | '/rota/swaps'
    | '/scheduling/dcs-oncall'
    | '/scheduling/maintenance'
    | '/scheduling/noc-shifts'
    | '/settings/automation'
    | '/settings/department-assignments'
    | '/settings/departments'
    | '/settings/escalation'
    | '/settings/general'
    | '/settings/leave-types'
    | '/settings/roles'
    | '/staff/$staffId'
    | '/timesheets/documents'
    | '/training/catalog'
    | '/training/events'
    | '/training/exams'
    | '/training/in-house'
    | '/training/plan'
    | '/training/vouchers'
    | '/work/$workItemId'
    | '/work/new'
    | '/work/workload'
    | '/access/'
    | '/advances/'
    | '/analytics/'
    | '/appraisals/'
    | '/attendance/'
    | '/audit/'
    | '/career-progression/'
    | '/changes/'
    | '/compliance/'
    | '/contracts/'
    | '/cycles/'
    | '/forms/'
    | '/hr/'
    | '/import/'
    | '/incidents/'
    | '/lateness/'
    | '/leave/'
    | '/noc-performance/'
    | '/notifications/'
    | '/ops-readiness/'
    | '/policy/'
    | '/procurement/'
    | '/reports/'
    | '/roster/'
    | '/rota/'
    | '/scheduling/'
    | '/services/'
    | '/settings/'
    | '/staff/'
    | '/timesheets/'
    | '/training/'
    | '/work/'
    | '/access/registry/$staffId'
    | '/appraisals/staff/$staffProfileId'
    | '/staff/$staffId/attendance'
    | '/rota/calendar/'
    | '/rota/fairness/'
    | '/rota/warnings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/profile'
    | '/'
    | '/access/$accountId'
    | '/access/platforms'
    | '/access/registry'
    | '/advances/$advanceId'
    | '/advances/new'
    | '/appraisals/$appraisalId'
    | '/appraisals/inbox'
    | '/attendance/holidays'
    | '/attendance/monthly'
    | '/attendance/roll-call'
    | '/changes/$changeId'
    | '/changes/new'
    | '/compliance/items'
    | '/compliance/ppe'
    | '/compliance/training'
    | '/contracts/$contractId'
    | '/cycles/$cycleId'
    | '/hr/ppe'
    | '/incidents/$incidentId'
    | '/incidents/new'
    | '/leave/balances'
    | '/leave/calendar'
    | '/leave/new'
    | '/leave/planner'
    | '/leave/tosd'
    | '/procurement/new'
    | '/roster/maintenance'
    | '/roster/my-roster'
    | '/roster/planner'
    | '/roster/swaps'
    | '/roster/today'
    | '/rota/history'
    | '/rota/planner'
    | '/rota/swaps'
    | '/scheduling/dcs-oncall'
    | '/scheduling/maintenance'
    | '/scheduling/noc-shifts'
    | '/settings/automation'
    | '/settings/department-assignments'
    | '/settings/departments'
    | '/settings/escalation'
    | '/settings/general'
    | '/settings/leave-types'
    | '/settings/roles'
    | '/staff/$staffId'
    | '/timesheets/documents'
    | '/training/catalog'
    | '/training/events'
    | '/training/exams'
    | '/training/in-house'
    | '/training/plan'
    | '/training/vouchers'
    | '/work/$workItemId'
    | '/work/new'
    | '/work/workload'
    | '/access'
    | '/advances'
    | '/analytics'
    | '/appraisals'
    | '/attendance'
    | '/audit'
    | '/career-progression'
    | '/changes'
    | '/compliance'
    | '/contracts'
    | '/cycles'
    | '/forms'
    | '/hr'
    | '/import'
    | '/incidents'
    | '/lateness'
    | '/leave'
    | '/noc-performance'
    | '/notifications'
    | '/ops-readiness'
    | '/policy'
    | '/procurement'
    | '/reports'
    | '/roster'
    | '/rota'
    | '/scheduling'
    | '/services'
    | '/settings'
    | '/staff'
    | '/timesheets'
    | '/training'
    | '/work'
    | '/access/registry/$staffId'
    | '/appraisals/staff/$staffProfileId'
    | '/staff/$staffId/attendance'
    | '/rota/calendar'
    | '/rota/fairness'
    | '/rota/warnings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/access/$accountId'
    | '/_authenticated/access/platforms'
    | '/_authenticated/access/registry'
    | '/_authenticated/advances/$advanceId'
    | '/_authenticated/advances/new'
    | '/_authenticated/appraisals/$appraisalId'
    | '/_authenticated/appraisals/inbox'
    | '/_authenticated/attendance/holidays'
    | '/_authenticated/attendance/monthly'
    | '/_authenticated/attendance/roll-call'
    | '/_authenticated/changes/$changeId'
    | '/_authenticated/changes/new'
    | '/_authenticated/compliance/items'
    | '/_authenticated/compliance/ppe'
    | '/_authenticated/compliance/training'
    | '/_authenticated/contracts/$contractId'
    | '/_authenticated/cycles/$cycleId'
    | '/_authenticated/hr/ppe'
    | '/_authenticated/incidents/$incidentId'
    | '/_authenticated/incidents/new'
    | '/_authenticated/leave/balances'
    | '/_authenticated/leave/calendar'
    | '/_authenticated/leave/new'
    | '/_authenticated/leave/planner'
    | '/_authenticated/leave/tosd'
    | '/_authenticated/procurement/new'
    | '/_authenticated/roster/maintenance'
    | '/_authenticated/roster/my-roster'
    | '/_authenticated/roster/planner'
    | '/_authenticated/roster/swaps'
    | '/_authenticated/roster/today'
    | '/_authenticated/rota/history'
    | '/_authenticated/rota/planner'
    | '/_authenticated/rota/swaps'
    | '/_authenticated/scheduling/dcs-oncall'
    | '/_authenticated/scheduling/maintenance'
    | '/_authenticated/scheduling/noc-shifts'
    | '/_authenticated/settings/automation'
    | '/_authenticated/settings/department-assignments'
    | '/_authenticated/settings/departments'
    | '/_authenticated/settings/escalation'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/leave-types'
    | '/_authenticated/settings/roles'
    | '/_authenticated/staff/$staffId'
    | '/_authenticated/timesheets/documents'
    | '/_authenticated/training/catalog'
    | '/_authenticated/training/events'
    | '/_authenticated/training/exams'
    | '/_authenticated/training/in-house'
    | '/_authenticated/training/plan'
    | '/_authenticated/training/vouchers'
    | '/_authenticated/work/$workItemId'
    | '/_authenticated/work/new'
    | '/_authenticated/work/workload'
    | '/_authenticated/access/'
    | '/_authenticated/advances/'
    | '/_authenticated/analytics/'
    | '/_authenticated/appraisals/'
    | '/_authenticated/attendance/'
    | '/_authenticated/audit/'
    | '/_authenticated/career-progression/'
    | '/_authenticated/changes/'
    | '/_authenticated/compliance/'
    | '/_authenticated/contracts/'
    | '/_authenticated/cycles/'
    | '/_authenticated/forms/'
    | '/_authenticated/hr/'
    | '/_authenticated/import/'
    | '/_authenticated/incidents/'
    | '/_authenticated/lateness/'
    | '/_authenticated/leave/'
    | '/_authenticated/noc-performance/'
    | '/_authenticated/notifications/'
    | '/_authenticated/ops-readiness/'
    | '/_authenticated/policy/'
    | '/_authenticated/procurement/'
    | '/_authenticated/reports/'
    | '/_authenticated/roster/'
    | '/_authenticated/rota/'
    | '/_authenticated/scheduling/'
    | '/_authenticated/services/'
    | '/_authenticated/settings/'
    | '/_authenticated/staff/'
    | '/_authenticated/timesheets/'
    | '/_authenticated/training/'
    | '/_authenticated/work/'
    | '/_authenticated/access/registry/$staffId'
    | '/_authenticated/appraisals/staff/$staffProfileId'
    | '/_authenticated/staff/$staffId/attendance'
    | '/_authenticated/rota/calendar/'
    | '/_authenticated/rota/fairness/'
    | '/_authenticated/rota/warnings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/': {
      id: '/_authenticated/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof AuthenticatedWorkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/': {
      id: '/_authenticated/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof AuthenticatedTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timesheets/': {
      id: '/_authenticated/timesheets/'
      path: '/timesheets'
      fullPath: '/timesheets/'
      preLoaderRoute: typeof AuthenticatedTimesheetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling/': {
      id: '/_authenticated/scheduling/'
      path: '/scheduling'
      fullPath: '/scheduling/'
      preLoaderRoute: typeof AuthenticatedSchedulingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/': {
      id: '/_authenticated/rota/'
      path: '/rota'
      fullPath: '/rota/'
      preLoaderRoute: typeof AuthenticatedRotaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/': {
      id: '/_authenticated/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof AuthenticatedRosterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/': {
      id: '/_authenticated/procurement/'
      path: '/procurement'
      fullPath: '/procurement/'
      preLoaderRoute: typeof AuthenticatedProcurementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/policy/': {
      id: '/_authenticated/policy/'
      path: '/policy'
      fullPath: '/policy/'
      preLoaderRoute: typeof AuthenticatedPolicyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops-readiness/': {
      id: '/_authenticated/ops-readiness/'
      path: '/ops-readiness'
      fullPath: '/ops-readiness/'
      preLoaderRoute: typeof AuthenticatedOpsReadinessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/noc-performance/': {
      id: '/_authenticated/noc-performance/'
      path: '/noc-performance'
      fullPath: '/noc-performance/'
      preLoaderRoute: typeof AuthenticatedNocPerformanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/': {
      id: '/_authenticated/leave/'
      path: '/leave'
      fullPath: '/leave/'
      preLoaderRoute: typeof AuthenticatedLeaveIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lateness/': {
      id: '/_authenticated/lateness/'
      path: '/lateness'
      fullPath: '/lateness/'
      preLoaderRoute: typeof AuthenticatedLatenessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/forms/': {
      id: '/_authenticated/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthenticatedFormsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cycles/': {
      id: '/_authenticated/cycles/'
      path: '/cycles'
      fullPath: '/cycles/'
      preLoaderRoute: typeof AuthenticatedCyclesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changes/': {
      id: '/_authenticated/changes/'
      path: '/changes'
      fullPath: '/changes/'
      preLoaderRoute: typeof AuthenticatedChangesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/career-progression/': {
      id: '/_authenticated/career-progression/'
      path: '/career-progression'
      fullPath: '/career-progression/'
      preLoaderRoute: typeof AuthenticatedCareerProgressionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisals/': {
      id: '/_authenticated/appraisals/'
      path: '/appraisals'
      fullPath: '/appraisals/'
      preLoaderRoute: typeof AuthenticatedAppraisalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advances/': {
      id: '/_authenticated/advances/'
      path: '/advances'
      fullPath: '/advances/'
      preLoaderRoute: typeof AuthenticatedAdvancesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/': {
      id: '/_authenticated/access/'
      path: '/access'
      fullPath: '/access/'
      preLoaderRoute: typeof AuthenticatedAccessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/workload': {
      id: '/_authenticated/work/workload'
      path: '/work/workload'
      fullPath: '/work/workload'
      preLoaderRoute: typeof AuthenticatedWorkWorkloadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/new': {
      id: '/_authenticated/work/new'
      path: '/work/new'
      fullPath: '/work/new'
      preLoaderRoute: typeof AuthenticatedWorkNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/$workItemId': {
      id: '/_authenticated/work/$workItemId'
      path: '/work/$workItemId'
      fullPath: '/work/$workItemId'
      preLoaderRoute: typeof AuthenticatedWorkWorkItemIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/vouchers': {
      id: '/_authenticated/training/vouchers'
      path: '/training/vouchers'
      fullPath: '/training/vouchers'
      preLoaderRoute: typeof AuthenticatedTrainingVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/plan': {
      id: '/_authenticated/training/plan'
      path: '/training/plan'
      fullPath: '/training/plan'
      preLoaderRoute: typeof AuthenticatedTrainingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/in-house': {
      id: '/_authenticated/training/in-house'
      path: '/training/in-house'
      fullPath: '/training/in-house'
      preLoaderRoute: typeof AuthenticatedTrainingInHouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/exams': {
      id: '/_authenticated/training/exams'
      path: '/training/exams'
      fullPath: '/training/exams'
      preLoaderRoute: typeof AuthenticatedTrainingExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/events': {
      id: '/_authenticated/training/events'
      path: '/training/events'
      fullPath: '/training/events'
      preLoaderRoute: typeof AuthenticatedTrainingEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training/catalog': {
      id: '/_authenticated/training/catalog'
      path: '/training/catalog'
      fullPath: '/training/catalog'
      preLoaderRoute: typeof AuthenticatedTrainingCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timesheets/documents': {
      id: '/_authenticated/timesheets/documents'
      path: '/timesheets/documents'
      fullPath: '/timesheets/documents'
      preLoaderRoute: typeof AuthenticatedTimesheetsDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$staffId': {
      id: '/_authenticated/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/leave-types': {
      id: '/_authenticated/settings/leave-types'
      path: '/settings/leave-types'
      fullPath: '/settings/leave-types'
      preLoaderRoute: typeof AuthenticatedSettingsLeaveTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/escalation': {
      id: '/_authenticated/settings/escalation'
      path: '/settings/escalation'
      fullPath: '/settings/escalation'
      preLoaderRoute: typeof AuthenticatedSettingsEscalationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/departments': {
      id: '/_authenticated/settings/departments'
      path: '/settings/departments'
      fullPath: '/settings/departments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/department-assignments': {
      id: '/_authenticated/settings/department-assignments'
      path: '/settings/department-assignments'
      fullPath: '/settings/department-assignments'
      preLoaderRoute: typeof AuthenticatedSettingsDepartmentAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/automation': {
      id: '/_authenticated/settings/automation'
      path: '/settings/automation'
      fullPath: '/settings/automation'
      preLoaderRoute: typeof AuthenticatedSettingsAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling/noc-shifts': {
      id: '/_authenticated/scheduling/noc-shifts'
      path: '/scheduling/noc-shifts'
      fullPath: '/scheduling/noc-shifts'
      preLoaderRoute: typeof AuthenticatedSchedulingNocShiftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling/maintenance': {
      id: '/_authenticated/scheduling/maintenance'
      path: '/scheduling/maintenance'
      fullPath: '/scheduling/maintenance'
      preLoaderRoute: typeof AuthenticatedSchedulingMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduling/dcs-oncall': {
      id: '/_authenticated/scheduling/dcs-oncall'
      path: '/scheduling/dcs-oncall'
      fullPath: '/scheduling/dcs-oncall'
      preLoaderRoute: typeof AuthenticatedSchedulingDcsOncallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/swaps': {
      id: '/_authenticated/rota/swaps'
      path: '/rota/swaps'
      fullPath: '/rota/swaps'
      preLoaderRoute: typeof AuthenticatedRotaSwapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/planner': {
      id: '/_authenticated/rota/planner'
      path: '/rota/planner'
      fullPath: '/rota/planner'
      preLoaderRoute: typeof AuthenticatedRotaPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/history': {
      id: '/_authenticated/rota/history'
      path: '/rota/history'
      fullPath: '/rota/history'
      preLoaderRoute: typeof AuthenticatedRotaHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/today': {
      id: '/_authenticated/roster/today'
      path: '/roster/today'
      fullPath: '/roster/today'
      preLoaderRoute: typeof AuthenticatedRosterTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/swaps': {
      id: '/_authenticated/roster/swaps'
      path: '/roster/swaps'
      fullPath: '/roster/swaps'
      preLoaderRoute: typeof AuthenticatedRosterSwapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/planner': {
      id: '/_authenticated/roster/planner'
      path: '/roster/planner'
      fullPath: '/roster/planner'
      preLoaderRoute: typeof AuthenticatedRosterPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/my-roster': {
      id: '/_authenticated/roster/my-roster'
      path: '/roster/my-roster'
      fullPath: '/roster/my-roster'
      preLoaderRoute: typeof AuthenticatedRosterMyRosterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roster/maintenance': {
      id: '/_authenticated/roster/maintenance'
      path: '/roster/maintenance'
      fullPath: '/roster/maintenance'
      preLoaderRoute: typeof AuthenticatedRosterMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/new': {
      id: '/_authenticated/procurement/new'
      path: '/procurement/new'
      fullPath: '/procurement/new'
      preLoaderRoute: typeof AuthenticatedProcurementNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/tosd': {
      id: '/_authenticated/leave/tosd'
      path: '/leave/tosd'
      fullPath: '/leave/tosd'
      preLoaderRoute: typeof AuthenticatedLeaveTosdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/planner': {
      id: '/_authenticated/leave/planner'
      path: '/leave/planner'
      fullPath: '/leave/planner'
      preLoaderRoute: typeof AuthenticatedLeavePlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/new': {
      id: '/_authenticated/leave/new'
      path: '/leave/new'
      fullPath: '/leave/new'
      preLoaderRoute: typeof AuthenticatedLeaveNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/calendar': {
      id: '/_authenticated/leave/calendar'
      path: '/leave/calendar'
      fullPath: '/leave/calendar'
      preLoaderRoute: typeof AuthenticatedLeaveCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leave/balances': {
      id: '/_authenticated/leave/balances'
      path: '/leave/balances'
      fullPath: '/leave/balances'
      preLoaderRoute: typeof AuthenticatedLeaveBalancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/new': {
      id: '/_authenticated/incidents/new'
      path: '/incidents/new'
      fullPath: '/incidents/new'
      preLoaderRoute: typeof AuthenticatedIncidentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/incidents/$incidentId': {
      id: '/_authenticated/incidents/$incidentId'
      path: '/incidents/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr/ppe': {
      id: '/_authenticated/hr/ppe'
      path: '/hr/ppe'
      fullPath: '/hr/ppe'
      preLoaderRoute: typeof AuthenticatedHrPpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cycles/$cycleId': {
      id: '/_authenticated/cycles/$cycleId'
      path: '/cycles/$cycleId'
      fullPath: '/cycles/$cycleId'
      preLoaderRoute: typeof AuthenticatedCyclesCycleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts/$contractId': {
      id: '/_authenticated/contracts/$contractId'
      path: '/contracts/$contractId'
      fullPath: '/contracts/$contractId'
      preLoaderRoute: typeof AuthenticatedContractsContractIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/training': {
      id: '/_authenticated/compliance/training'
      path: '/compliance/training'
      fullPath: '/compliance/training'
      preLoaderRoute: typeof AuthenticatedComplianceTrainingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/ppe': {
      id: '/_authenticated/compliance/ppe'
      path: '/compliance/ppe'
      fullPath: '/compliance/ppe'
      preLoaderRoute: typeof AuthenticatedCompliancePpeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/items': {
      id: '/_authenticated/compliance/items'
      path: '/compliance/items'
      fullPath: '/compliance/items'
      preLoaderRoute: typeof AuthenticatedComplianceItemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changes/new': {
      id: '/_authenticated/changes/new'
      path: '/changes/new'
      fullPath: '/changes/new'
      preLoaderRoute: typeof AuthenticatedChangesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/changes/$changeId': {
      id: '/_authenticated/changes/$changeId'
      path: '/changes/$changeId'
      fullPath: '/changes/$changeId'
      preLoaderRoute: typeof AuthenticatedChangesChangeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/roll-call': {
      id: '/_authenticated/attendance/roll-call'
      path: '/attendance/roll-call'
      fullPath: '/attendance/roll-call'
      preLoaderRoute: typeof AuthenticatedAttendanceRollCallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/monthly': {
      id: '/_authenticated/attendance/monthly'
      path: '/attendance/monthly'
      fullPath: '/attendance/monthly'
      preLoaderRoute: typeof AuthenticatedAttendanceMonthlyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance/holidays': {
      id: '/_authenticated/attendance/holidays'
      path: '/attendance/holidays'
      fullPath: '/attendance/holidays'
      preLoaderRoute: typeof AuthenticatedAttendanceHolidaysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisals/inbox': {
      id: '/_authenticated/appraisals/inbox'
      path: '/appraisals/inbox'
      fullPath: '/appraisals/inbox'
      preLoaderRoute: typeof AuthenticatedAppraisalsInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appraisals/$appraisalId': {
      id: '/_authenticated/appraisals/$appraisalId'
      path: '/appraisals/$appraisalId'
      fullPath: '/appraisals/$appraisalId'
      preLoaderRoute: typeof AuthenticatedAppraisalsAppraisalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advances/new': {
      id: '/_authenticated/advances/new'
      path: '/advances/new'
      fullPath: '/advances/new'
      preLoaderRoute: typeof AuthenticatedAdvancesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advances/$advanceId': {
      id: '/_authenticated/advances/$advanceId'
      path: '/advances/$advanceId'
      fullPath: '/advances/$advanceId'
      preLoaderRoute: typeof AuthenticatedAdvancesAdvanceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/registry': {
      id: '/_authenticated/access/registry'
      path: '/access/registry'
      fullPath: '/access/registry'
      preLoaderRoute: typeof AuthenticatedAccessRegistryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/platforms': {
      id: '/_authenticated/access/platforms'
      path: '/access/platforms'
      fullPath: '/access/platforms'
      preLoaderRoute: typeof AuthenticatedAccessPlatformsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/$accountId': {
      id: '/_authenticated/access/$accountId'
      path: '/access/$accountId'
      fullPath: '/access/$accountId'
      preLoaderRoute: typeof AuthenticatedAccessAccountIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/warnings/': {
      id: '/_authenticated/rota/warnings/'
      path: '/rota/warnings'
      fullPath: '/rota/warnings/'
      preLoaderRoute: typeof AuthenticatedRotaWarningsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/fairness/': {
      id: '/_authenticated/rota/fairness/'
      path: '/rota/fairness'
      fullPath: '/rota/fairness/'
      preLoaderRoute: typeof AuthenticatedRotaFairnessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rota/calendar/': {
      id: '/_authenticated/rota/calendar/'
      path: '/rota/calendar'
      fullPath: '/rota/calendar/'
      preLoaderRoute: typeof AuthenticatedRotaCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/$staffId/attendance': {
      id: '/_authenticated/staff/$staffId/attendance'
      path: '/attendance'
      fullPath: '/staff/$staffId/attendance'
      preLoaderRoute: typeof AuthenticatedStaffStaffIdAttendanceRouteImport
      parentRoute: typeof AuthenticatedStaffStaffIdRoute
    }
    '/_authenticated/appraisals/staff/$staffProfileId': {
      id: '/_authenticated/appraisals/staff/$staffProfileId'
      path: '/appraisals/staff/$staffProfileId'
      fullPath: '/appraisals/staff/$staffProfileId'
      preLoaderRoute: typeof AuthenticatedAppraisalsStaffStaffProfileIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/access/registry/$staffId': {
      id: '/_authenticated/access/registry/$staffId'
      path: '/$staffId'
      fullPath: '/access/registry/$staffId'
      preLoaderRoute: typeof AuthenticatedAccessRegistryStaffIdRouteImport
      parentRoute: typeof AuthenticatedAccessRegistryRoute
    }
  }
}

interface AuthenticatedAccessRegistryRouteChildren {
  AuthenticatedAccessRegistryStaffIdRoute: typeof AuthenticatedAccessRegistryStaffIdRoute
}

const AuthenticatedAccessRegistryRouteChildren: AuthenticatedAccessRegistryRouteChildren =
  {
    AuthenticatedAccessRegistryStaffIdRoute:
      AuthenticatedAccessRegistryStaffIdRoute,
  }

const AuthenticatedAccessRegistryRouteWithChildren =
  AuthenticatedAccessRegistryRoute._addFileChildren(
    AuthenticatedAccessRegistryRouteChildren,
  )

interface AuthenticatedStaffStaffIdRouteChildren {
  AuthenticatedStaffStaffIdAttendanceRoute: typeof AuthenticatedStaffStaffIdAttendanceRoute
}

const AuthenticatedStaffStaffIdRouteChildren: AuthenticatedStaffStaffIdRouteChildren =
  {
    AuthenticatedStaffStaffIdAttendanceRoute:
      AuthenticatedStaffStaffIdAttendanceRoute,
  }

const AuthenticatedStaffStaffIdRouteWithChildren =
  AuthenticatedStaffStaffIdRoute._addFileChildren(
    AuthenticatedStaffStaffIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccessAccountIdRoute: typeof AuthenticatedAccessAccountIdRoute
  AuthenticatedAccessPlatformsRoute: typeof AuthenticatedAccessPlatformsRoute
  AuthenticatedAccessRegistryRoute: typeof AuthenticatedAccessRegistryRouteWithChildren
  AuthenticatedAdvancesAdvanceIdRoute: typeof AuthenticatedAdvancesAdvanceIdRoute
  AuthenticatedAdvancesNewRoute: typeof AuthenticatedAdvancesNewRoute
  AuthenticatedAppraisalsAppraisalIdRoute: typeof AuthenticatedAppraisalsAppraisalIdRoute
  AuthenticatedAppraisalsInboxRoute: typeof AuthenticatedAppraisalsInboxRoute
  AuthenticatedAttendanceHolidaysRoute: typeof AuthenticatedAttendanceHolidaysRoute
  AuthenticatedAttendanceMonthlyRoute: typeof AuthenticatedAttendanceMonthlyRoute
  AuthenticatedAttendanceRollCallRoute: typeof AuthenticatedAttendanceRollCallRoute
  AuthenticatedChangesChangeIdRoute: typeof AuthenticatedChangesChangeIdRoute
  AuthenticatedChangesNewRoute: typeof AuthenticatedChangesNewRoute
  AuthenticatedComplianceItemsRoute: typeof AuthenticatedComplianceItemsRoute
  AuthenticatedCompliancePpeRoute: typeof AuthenticatedCompliancePpeRoute
  AuthenticatedComplianceTrainingRoute: typeof AuthenticatedComplianceTrainingRoute
  AuthenticatedContractsContractIdRoute: typeof AuthenticatedContractsContractIdRoute
  AuthenticatedCyclesCycleIdRoute: typeof AuthenticatedCyclesCycleIdRoute
  AuthenticatedHrPpeRoute: typeof AuthenticatedHrPpeRoute
  AuthenticatedIncidentsIncidentIdRoute: typeof AuthenticatedIncidentsIncidentIdRoute
  AuthenticatedIncidentsNewRoute: typeof AuthenticatedIncidentsNewRoute
  AuthenticatedLeaveBalancesRoute: typeof AuthenticatedLeaveBalancesRoute
  AuthenticatedLeaveCalendarRoute: typeof AuthenticatedLeaveCalendarRoute
  AuthenticatedLeaveNewRoute: typeof AuthenticatedLeaveNewRoute
  AuthenticatedLeavePlannerRoute: typeof AuthenticatedLeavePlannerRoute
  AuthenticatedLeaveTosdRoute: typeof AuthenticatedLeaveTosdRoute
  AuthenticatedProcurementNewRoute: typeof AuthenticatedProcurementNewRoute
  AuthenticatedRosterMaintenanceRoute: typeof AuthenticatedRosterMaintenanceRoute
  AuthenticatedRosterMyRosterRoute: typeof AuthenticatedRosterMyRosterRoute
  AuthenticatedRosterPlannerRoute: typeof AuthenticatedRosterPlannerRoute
  AuthenticatedRosterSwapsRoute: typeof AuthenticatedRosterSwapsRoute
  AuthenticatedRosterTodayRoute: typeof AuthenticatedRosterTodayRoute
  AuthenticatedRotaHistoryRoute: typeof AuthenticatedRotaHistoryRoute
  AuthenticatedRotaPlannerRoute: typeof AuthenticatedRotaPlannerRoute
  AuthenticatedRotaSwapsRoute: typeof AuthenticatedRotaSwapsRoute
  AuthenticatedSchedulingDcsOncallRoute: typeof AuthenticatedSchedulingDcsOncallRoute
  AuthenticatedSchedulingMaintenanceRoute: typeof AuthenticatedSchedulingMaintenanceRoute
  AuthenticatedSchedulingNocShiftsRoute: typeof AuthenticatedSchedulingNocShiftsRoute
  AuthenticatedSettingsAutomationRoute: typeof AuthenticatedSettingsAutomationRoute
  AuthenticatedSettingsDepartmentAssignmentsRoute: typeof AuthenticatedSettingsDepartmentAssignmentsRoute
  AuthenticatedSettingsDepartmentsRoute: typeof AuthenticatedSettingsDepartmentsRoute
  AuthenticatedSettingsEscalationRoute: typeof AuthenticatedSettingsEscalationRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsLeaveTypesRoute: typeof AuthenticatedSettingsLeaveTypesRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedStaffStaffIdRoute: typeof AuthenticatedStaffStaffIdRouteWithChildren
  AuthenticatedTimesheetsDocumentsRoute: typeof AuthenticatedTimesheetsDocumentsRoute
  AuthenticatedTrainingCatalogRoute: typeof AuthenticatedTrainingCatalogRoute
  AuthenticatedTrainingEventsRoute: typeof AuthenticatedTrainingEventsRoute
  AuthenticatedTrainingExamsRoute: typeof AuthenticatedTrainingExamsRoute
  AuthenticatedTrainingInHouseRoute: typeof AuthenticatedTrainingInHouseRoute
  AuthenticatedTrainingPlanRoute: typeof AuthenticatedTrainingPlanRoute
  AuthenticatedTrainingVouchersRoute: typeof AuthenticatedTrainingVouchersRoute
  AuthenticatedWorkWorkItemIdRoute: typeof AuthenticatedWorkWorkItemIdRoute
  AuthenticatedWorkNewRoute: typeof AuthenticatedWorkNewRoute
  AuthenticatedWorkWorkloadRoute: typeof AuthenticatedWorkWorkloadRoute
  AuthenticatedAccessIndexRoute: typeof AuthenticatedAccessIndexRoute
  AuthenticatedAdvancesIndexRoute: typeof AuthenticatedAdvancesIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedAppraisalsIndexRoute: typeof AuthenticatedAppraisalsIndexRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedCareerProgressionIndexRoute: typeof AuthenticatedCareerProgressionIndexRoute
  AuthenticatedChangesIndexRoute: typeof AuthenticatedChangesIndexRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedCyclesIndexRoute: typeof AuthenticatedCyclesIndexRoute
  AuthenticatedFormsIndexRoute: typeof AuthenticatedFormsIndexRoute
  AuthenticatedHrIndexRoute: typeof AuthenticatedHrIndexRoute
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
  AuthenticatedLatenessIndexRoute: typeof AuthenticatedLatenessIndexRoute
  AuthenticatedLeaveIndexRoute: typeof AuthenticatedLeaveIndexRoute
  AuthenticatedNocPerformanceIndexRoute: typeof AuthenticatedNocPerformanceIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOpsReadinessIndexRoute: typeof AuthenticatedOpsReadinessIndexRoute
  AuthenticatedPolicyIndexRoute: typeof AuthenticatedPolicyIndexRoute
  AuthenticatedProcurementIndexRoute: typeof AuthenticatedProcurementIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedRosterIndexRoute: typeof AuthenticatedRosterIndexRoute
  AuthenticatedRotaIndexRoute: typeof AuthenticatedRotaIndexRoute
  AuthenticatedSchedulingIndexRoute: typeof AuthenticatedSchedulingIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedTimesheetsIndexRoute: typeof AuthenticatedTimesheetsIndexRoute
  AuthenticatedTrainingIndexRoute: typeof AuthenticatedTrainingIndexRoute
  AuthenticatedWorkIndexRoute: typeof AuthenticatedWorkIndexRoute
  AuthenticatedAppraisalsStaffStaffProfileIdRoute: typeof AuthenticatedAppraisalsStaffStaffProfileIdRoute
  AuthenticatedRotaCalendarIndexRoute: typeof AuthenticatedRotaCalendarIndexRoute
  AuthenticatedRotaFairnessIndexRoute: typeof AuthenticatedRotaFairnessIndexRoute
  AuthenticatedRotaWarningsIndexRoute: typeof AuthenticatedRotaWarningsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccessAccountIdRoute: AuthenticatedAccessAccountIdRoute,
  AuthenticatedAccessPlatformsRoute: AuthenticatedAccessPlatformsRoute,
  AuthenticatedAccessRegistryRoute:
    AuthenticatedAccessRegistryRouteWithChildren,
  AuthenticatedAdvancesAdvanceIdRoute: AuthenticatedAdvancesAdvanceIdRoute,
  AuthenticatedAdvancesNewRoute: AuthenticatedAdvancesNewRoute,
  AuthenticatedAppraisalsAppraisalIdRoute:
    AuthenticatedAppraisalsAppraisalIdRoute,
  AuthenticatedAppraisalsInboxRoute: AuthenticatedAppraisalsInboxRoute,
  AuthenticatedAttendanceHolidaysRoute: AuthenticatedAttendanceHolidaysRoute,
  AuthenticatedAttendanceMonthlyRoute: AuthenticatedAttendanceMonthlyRoute,
  AuthenticatedAttendanceRollCallRoute: AuthenticatedAttendanceRollCallRoute,
  AuthenticatedChangesChangeIdRoute: AuthenticatedChangesChangeIdRoute,
  AuthenticatedChangesNewRoute: AuthenticatedChangesNewRoute,
  AuthenticatedComplianceItemsRoute: AuthenticatedComplianceItemsRoute,
  AuthenticatedCompliancePpeRoute: AuthenticatedCompliancePpeRoute,
  AuthenticatedComplianceTrainingRoute: AuthenticatedComplianceTrainingRoute,
  AuthenticatedContractsContractIdRoute: AuthenticatedContractsContractIdRoute,
  AuthenticatedCyclesCycleIdRoute: AuthenticatedCyclesCycleIdRoute,
  AuthenticatedHrPpeRoute: AuthenticatedHrPpeRoute,
  AuthenticatedIncidentsIncidentIdRoute: AuthenticatedIncidentsIncidentIdRoute,
  AuthenticatedIncidentsNewRoute: AuthenticatedIncidentsNewRoute,
  AuthenticatedLeaveBalancesRoute: AuthenticatedLeaveBalancesRoute,
  AuthenticatedLeaveCalendarRoute: AuthenticatedLeaveCalendarRoute,
  AuthenticatedLeaveNewRoute: AuthenticatedLeaveNewRoute,
  AuthenticatedLeavePlannerRoute: AuthenticatedLeavePlannerRoute,
  AuthenticatedLeaveTosdRoute: AuthenticatedLeaveTosdRoute,
  AuthenticatedProcurementNewRoute: AuthenticatedProcurementNewRoute,
  AuthenticatedRosterMaintenanceRoute: AuthenticatedRosterMaintenanceRoute,
  AuthenticatedRosterMyRosterRoute: AuthenticatedRosterMyRosterRoute,
  AuthenticatedRosterPlannerRoute: AuthenticatedRosterPlannerRoute,
  AuthenticatedRosterSwapsRoute: AuthenticatedRosterSwapsRoute,
  AuthenticatedRosterTodayRoute: AuthenticatedRosterTodayRoute,
  AuthenticatedRotaHistoryRoute: AuthenticatedRotaHistoryRoute,
  AuthenticatedRotaPlannerRoute: AuthenticatedRotaPlannerRoute,
  AuthenticatedRotaSwapsRoute: AuthenticatedRotaSwapsRoute,
  AuthenticatedSchedulingDcsOncallRoute: AuthenticatedSchedulingDcsOncallRoute,
  AuthenticatedSchedulingMaintenanceRoute:
    AuthenticatedSchedulingMaintenanceRoute,
  AuthenticatedSchedulingNocShiftsRoute: AuthenticatedSchedulingNocShiftsRoute,
  AuthenticatedSettingsAutomationRoute: AuthenticatedSettingsAutomationRoute,
  AuthenticatedSettingsDepartmentAssignmentsRoute:
    AuthenticatedSettingsDepartmentAssignmentsRoute,
  AuthenticatedSettingsDepartmentsRoute: AuthenticatedSettingsDepartmentsRoute,
  AuthenticatedSettingsEscalationRoute: AuthenticatedSettingsEscalationRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsLeaveTypesRoute: AuthenticatedSettingsLeaveTypesRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedStaffStaffIdRoute: AuthenticatedStaffStaffIdRouteWithChildren,
  AuthenticatedTimesheetsDocumentsRoute: AuthenticatedTimesheetsDocumentsRoute,
  AuthenticatedTrainingCatalogRoute: AuthenticatedTrainingCatalogRoute,
  AuthenticatedTrainingEventsRoute: AuthenticatedTrainingEventsRoute,
  AuthenticatedTrainingExamsRoute: AuthenticatedTrainingExamsRoute,
  AuthenticatedTrainingInHouseRoute: AuthenticatedTrainingInHouseRoute,
  AuthenticatedTrainingPlanRoute: AuthenticatedTrainingPlanRoute,
  AuthenticatedTrainingVouchersRoute: AuthenticatedTrainingVouchersRoute,
  AuthenticatedWorkWorkItemIdRoute: AuthenticatedWorkWorkItemIdRoute,
  AuthenticatedWorkNewRoute: AuthenticatedWorkNewRoute,
  AuthenticatedWorkWorkloadRoute: AuthenticatedWorkWorkloadRoute,
  AuthenticatedAccessIndexRoute: AuthenticatedAccessIndexRoute,
  AuthenticatedAdvancesIndexRoute: AuthenticatedAdvancesIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedAppraisalsIndexRoute: AuthenticatedAppraisalsIndexRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedCareerProgressionIndexRoute:
    AuthenticatedCareerProgressionIndexRoute,
  AuthenticatedChangesIndexRoute: AuthenticatedChangesIndexRoute,
  AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedCyclesIndexRoute: AuthenticatedCyclesIndexRoute,
  AuthenticatedFormsIndexRoute: AuthenticatedFormsIndexRoute,
  AuthenticatedHrIndexRoute: AuthenticatedHrIndexRoute,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  AuthenticatedLatenessIndexRoute: AuthenticatedLatenessIndexRoute,
  AuthenticatedLeaveIndexRoute: AuthenticatedLeaveIndexRoute,
  AuthenticatedNocPerformanceIndexRoute: AuthenticatedNocPerformanceIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOpsReadinessIndexRoute: AuthenticatedOpsReadinessIndexRoute,
  AuthenticatedPolicyIndexRoute: AuthenticatedPolicyIndexRoute,
  AuthenticatedProcurementIndexRoute: AuthenticatedProcurementIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedRosterIndexRoute: AuthenticatedRosterIndexRoute,
  AuthenticatedRotaIndexRoute: AuthenticatedRotaIndexRoute,
  AuthenticatedSchedulingIndexRoute: AuthenticatedSchedulingIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedTimesheetsIndexRoute: AuthenticatedTimesheetsIndexRoute,
  AuthenticatedTrainingIndexRoute: AuthenticatedTrainingIndexRoute,
  AuthenticatedWorkIndexRoute: AuthenticatedWorkIndexRoute,
  AuthenticatedAppraisalsStaffStaffProfileIdRoute:
    AuthenticatedAppraisalsStaffStaffProfileIdRoute,
  AuthenticatedRotaCalendarIndexRoute: AuthenticatedRotaCalendarIndexRoute,
  AuthenticatedRotaFairnessIndexRoute: AuthenticatedRotaFairnessIndexRoute,
  AuthenticatedRotaWarningsIndexRoute: AuthenticatedRotaWarningsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
